apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::292110682427:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-WFTDLWFML21P
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-09T18:06:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "841"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 42d924a9-638c-4df6-b459-e3104d6ca6c4
